### ISSUE TITLE
Working on Windows ?

### ISSUE THREAD

**Issue by Trollken-zz** [kenhys/sylpheed-htmlview#1]
Hi all,

First of all, thanks for the work done by making this plugin for sylpheed.

I just have a simple question : i saw in the NEWS file that Windows was supported.

So, my question is : how do i install it ?

Thanks in advance ! :).

**Comment by kenhys** [comment]
Hi.
There is no sophisticated way to install this plugin.
But I had compiled it for windows few months ago, there is a zip archive here.
http://gigo-ice.org/tech/sylpheed/htmlview/index.html
Note that  it does not contain dlls which htmlview plugin requires. you have to collect such precompiled dlls (gtkhtml,gail,grux and so on).
When I tried to compile it by myself, I can't enable some features of gtkhtml, so I didn't distribute all in one package at that time.

**Comment by kenhys** [comment]
Currently, Windows doesn't supported yet.

**Comment by Hibou57** [comment]
Claws Mail is supported on Windows, and it has an HTML view capability via a plugin. This may be a work around for the OP.

**Comment by sergeevabc** [comment]
It is 2017 now. What about HTML render in Sylpheed? Any ETA?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by MaximKiselev** [comment]
> Hi. There is no sophisticated way to install this plugin. But I had compiled it for windows few months ago, there is a zip archive here. http://gigo-ice.org/tech/sylpheed/htmlview/index.html Note that it does not contain dlls which htmlview plugin requires. you have to collect such precompiled dlls (gtkhtml,gail,grux and so on). When I tried to compile it by myself, I can't enable some features of gtkhtml, so I didn't distribute all in one package at that time.

hi, is there any chance to get .dll on windows? the site is not working

**Comment by kenhys** [comment]
> hi, is there any chance to get .dll on windows? the site is not working

Now I don't have that domain anymore and the same time, don't have prebuild archive anymore.

As other's advice, using Claws Mail might be better alternative.
