### ISSUE TITLE
Update documentation to include sylpheed-plugin-factory

### ISSUE THREAD

**Issue by tliron** [kenhys/sylpheed-htmlview#4]
It seems that current builds require this project, too: https://github.com/kenhys/sylpheed-plugin-factory

**Comment by kenhys** [comment]
Thanks, @tliron.

Install instruction is outdated, I've fixed it by https://github.com/kenhys/sylpheed-htmlview/commit/f62881d34761974cc97e061d81f47a72332d5178.
